language:
- python
python:
- '3.6'
install:
- pip3 install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: Amhss/dhX3Z1Iv4+vgX+LsQARLTjWBtkxIMIz73XXyIwWPPGXAGLJyMdpSUfb/uAMIf3H7o3A2TFMGd8LGgMt3dZJ+XWYFSHwmzo0bZfGZCc700h+nKz/lJVygwy5hCv7IUfD5g/uD+f4CWW5dpQOL57QyznjhRM+jHxDxx4X+HOny0PgcYNyG8/6jhhYTWOyudX3p7y9SnPrv8y/EYjjL+B6UCKwvHOm0ucZ/InskUc/Qc6Y3P0AwiIOpeEcKxkDUzCH8882RNP392mt6OYwX2VpEyBKnVCW+hoabioMk1EusUclByfP/NwBA1DNZz2kvaxQKhHcct92hJfvPm8UEIEANQBYw9L8sShoZnSE16we9febdWckLS7ege1ZZlkxGf/aWx3rn1IL1w8hEH0XrMVyV9chBvbiIYp8HAGz4jBLQeX3XHHHXL1vCB1eD7xtjxKMZP2xXTnBj5boGo95pDQLUH/ALj5zJEY5qtWK4QngSoso8NKzuj9ghNS2rglYDCZTRQ2mecTA56Ww6VMB9/NxlDh7cRtpdbyJd2FUUtAT1qqOmlA47XhJ3dqugB7kDybugO85edsX1O2EdbF7IJJB54J6aEhcAHlkwChROwgfy+HE1/bmbQo/5kMAxFHwFExb32bbKg0g8IIiFlvMYVUABcayynP3XfPtkWKTTA=
  app: flasktaskr-dima
  on:
    branch: master
    repo: qwerty432/flasktaskr
